trigger:
- main  # or your branch

pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Build the SpecFlow Project (with Restore)'
  inputs:
    command: 'build'
    projects: '**/SpecFlow_BrowserStack.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run SpecFlow NUnit Tests'
  inputs:
    command: 'test'
    projects: '**/SpecFlow_BrowserStack.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'
    publishTestResults: true
  env:
    BROWSERSTACK_USERNAME: $(BROWSERSTACK_USERNAME)
    BROWSERSTACK_ACCESS_KEY: $(BROWSERSTACK_ACCESS_KEY)
